## ConfigMaps
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: autobrr-config
data:
  AUTOBRR__PORT: "7474"
  AUTOBRR__HOST: "0.0.0.0"
  
  
## Service
---
apiVersion: v1
kind: Service
metadata:
   name: autobrr
   namespace: mediaserver
   labels:
     app.kubernetes.io/name: autobrr
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 7474
    name: http-7474
  selector:
    app.kubernetes.io/name: autobrr


## StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: autobrr
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: autobrr
  serviceName: "autobrr"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app.kubernetes.io/name: autobrr
    spec:
      containers:
      - name: autobrr
        image: ghcr.io/autobrr/autobrr:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: autobrr-config
        ports:
        - containerPort: 7474
          name: http-7474
        volumeMounts:
        - name: autobrr-config
          mountPath: "/config"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: autobrr-config
        persistentVolumeClaim:
          claimName: autobrr-config


## Volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autobrr-config
  namespace: mediaserver
  labels:
    name: autobrr-config
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi