apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mediaserver-farh-net-cert-letsencrypt
spec:
  # secretName doesn't have to match the certificate name, but it may as well, for simplicity!
  secretName: mediaserver-farh-net-cert-letsencrypt
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "false"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "false"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - "mediaserver.farh.net"
