apiVersion: v1
kind: ConfigMap
metadata:
  name: jellyfin-values
data:
  values.yaml: |
    replicaCount: 1
    #nameOverride: ""
    #fullnameOverride: ""

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      className: "traefik-external"
      hosts:
        - host: backroom.farh.net
          paths:
              - path: /
                pathType: Prefix
                service:
                  name:
                  port: 8096
      tls:
       - secretName: backroom-farh-net-cert
         hosts:
           - backroom.farh.net

    resources:
      requests:
        cpu: 2000m
        memory: 4Gi
      limits:
        cpu: 4000m
        memory: 8Gi
        gpu.intel.com/i915: 2

    volumes:
      - name: adult0
        persistentVolumeClaim:
          claimName: adult0

    volumeMounts:
      - name: adult0
        mountPath: "/media/adult0"
        readOnly: false

    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config
      media:
        enabled: false

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: farh.net/intel-gpu-gen
              operator: Gt
              values:
              - "11"