apiVersion: v1
kind: ConfigMap
metadata:
  name: jellyfin-values
data:
  values.yaml: |
    replicaCount: 1
    #nameOverride: ""
    #fullnameOverride: ""

    ingress:
      enabled: true
      className: "traefik-external"
      hosts:
        - host: backroom.farh.net
          paths:
              - path: /
                pathType: Prefix
                service:
                  name:
                  port: 8096
      tls:
       - secretName: backroom-farh-net-cert
         hosts:
           - backroom.farh.net

    resources:
      requests:
        cpu: 2000m
        memory: 4Gi
      limits:
        cpu: 4000m
        memory: 8Gi
        gpu.intel.com/i915: 1

    volumes:
      - name: adult
        persistentVolumeClaim:
          claimName: adult

    volumeMounts:
      - name: adult
        mountPath: "/media/adult"
        readOnly: false

    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 8Gi
        storageClass: 'ceph-block'
      media:
        enabled: false
