apiVersion: v1
kind: ConfigMap
metadata:
  name: clusterplex-values
data:
  values.yaml: |
    global:
      plexImage:
        repository: linuxserver/plex
        tag: latest
        imagePullPolicy: Always
      timezone: America/Detroit
      PGID: 911
      PUID: 911
      sharedStorage:
        transcode:
          enabled: true
          storageClass: "ceph-filesystem"
          size: 128Gi
          retain: true
        media:
          enabled: false
        additionalMediaVolumes:
          music0:
            enabled: true
            existingClaim: "music0"
            mountPath: /media/music0
          shows0:
            enabled: true
            existingClaim: "shows0"
            mountPath: /media/shows0
          shows:
            enabled: true
            existingClaim: "shows"
            mountPath: /media/shows
          movies:
            enabled: true
            existingClaim: "movies"
            mountPath: /media/movies
          movies0:
            enabled: true
            existingClaim: "movies0"
            mountPath: /media/movies0

    pms:
      enabled: true
      env: {}
      config:
        transcoderVerbose: 0
        transcodeOperatingMode: both
        plexClaimToken:
        version: latest
        localRelayEnabled: true
        port: 32400
        relayPort: 32499
        pmsIP: ""
      serviceConfig:
        annotations:
          service.cilium.io/forwarding-mode: dsr
        type: LoadBalancer
        externalTrafficPolicy: Local
      ingressConfig:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        labels:
          zone: public
        ingressClassName: "traefik-external"
        hosts:
          - host: redfleet.farh.net
            paths:
              - path: /
                pathType: Prefix
                service:
                  name:
                  port: 32400
        tls:
         - secretName: redfleet-farh-net-cert
           hosts:
             - redfleet.farh.net
      configVolume:
        enabled: true
        storageClass: "ceph-block"
        accessMode: ReadWriteOnce
        size: 32Gi
        retain: true
      healthProbes:
        startup: true
        readiness: true
        liveness: true
      resources:
        requests:
          cpu: 2000m
          memory: 4Gi
        limits:
          memory: 8Gi
          gpu.intel.com/i915: 2
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: farh.net/gpu
                operator: In
                values:
                - "true"
          
    orchestrator:
      enabled: true
      image:
        repository: ghcr.io/pabloromeo/clusterplex_orchestrator
        pullPolicy: IfNotPresent
      env: {}
      config:
        port: 3500
        workerSelectionStrategy: LOAD_TASKS
      serviceConfig:
        annotations:
          service.cilium.io/forwarding-mode: dsr
        labels: {}
        type: LoadBalancer
        externalTrafficPolicy: Local
      prometheusServiceMonitor:
        enabled: false
      enableGrafanaDashboard: false
      healthProbes:
        startup: true
        readiness: true
        liveness: true
      resources:
        requests:
          cpu: 200m
          memory: 64Mi
        limits:
          memory: 128Mi

    worker:
      enabled: false
      securityContext:
        privileged: true
      config:
        replicas: 2
        port: 3501
        cpuStatInterval: 1000
        eaeSupport: 1
      serviceConfig:
        annotations: 
          service.cilium.io/forwarding-mode: dsr
        labels: {}
        type: LoadBalancer
        externalTrafficPolicy: Local
      codecVolumes:
        enabled: true
        labels: {}
        annotations: {}
        accessMode: ReadWriteOnce
        size: 1Gi
      healthProbes:
        startup: true
        readiness: true
        liveness: true
      resources:
        requests:
          cpu: 2000m
          memory: 4Gi
        limits:
          memory: 8Gi
          gpu.intel.com/i915: 1
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: farh.net/gpu
                operator: In
                values:
                - "yes"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  name: clusterplex-worker
              topologyKey: kubernetes.io/hostname
            weight: 100
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  name: clusterplex-pms
              topologyKey: kubernetes.io/hostname
            weight: 50
