apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission-config
  namespace: mediaserver
data:
  LOCAL_NETWORK: "10.0.0.0/8"
  OPENVPN_COUNTRY: US
  OPENVPN_CITY: Detroit
  OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
  OPENVPN_PROVIDER: NORDVPN
  NORDVPN_COUNTRY: US
  NORDVPN_CATEGORY: legacy_p2p
  NORDVPN_PROTOCOL: udp
  TRANSMISSION_DOWNLOAD_DIR: "/downloads/complete"
  TRANSMISSION_INCOMPLETE_DIR: "/downloads/incomplete"
  TRANSMISSION_INCOMPLETE_DIR_ENABLED: "true"
  TRANSMISSION_DOWNLOAD_QUEUE_SIZE: "8"
  TRANSMISSION_CACHE_SIZE_MB: "128"
  TRANSMISSION_RATIO_LIMIT: "2"
  TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
  TRANSMISSION_SPEED_LIMIT_DOWN: "50000"
  TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED: "true"
  TRANSMISSION_SPEED_LIMIT_UP: "50000"
  TRANSMISSION_SPEED_LIMIT_UP_ENABLED: "true"
  TRANSMISSION_UTP_ENABLED: "true"
  WEBPROXY_ENABLED: "false"
  DEBUG: "true"