### Service
---
apiVersion: v1
kind: Service
metadata:
  name: fileserver
  namespace: mediaserver
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 20048
  - name: rpcbind
    port: 111
  selector:
    app: fileserver # must match with the label of NFS pod
---


## Deployments
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fileserver
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: fileserver
  template:
    metadata:
      labels:
        app: fileserver
    spec:
      containers:
      - name: nfs-server
        image: k8s.gcr.io/volume-nfs:0.8
        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /exports
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn-perpetual"
      resources:
        requests:
          storage: 128Gi