### Service
---
apiVersion: v1
kind: Service
metadata:
  name: fileserver
  namespace: mediaserver
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 20048
  - name: rpcbind
    port: 111
  selector:
    app: fileserver # must match with the label of NFS pod
---


## Deployments
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileserver
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: fileserver
  template:
    metadata:
      labels:
        app: fileserver
    spec:
      containers:
      - name: nfs-server
        image: k8s.gcr.io/volume-nfs:0.8
        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
        - name: movies
          mountPath: /exports/movies
        - name: shows
          mountPath: /exports/shows
        - name: anime-movies
          mountPath: /exports/anime-movies
        - name: anime-shows
          mountPath: /exports/anime-shows
      volumes:
        - name: shows
          persistentVolumeClaim:
            claimName: fileserver-shows
        - name: movies
          persistentVolumeClaim:
            claimName: fileserver-movies
        - name: anime-shows
          persistentVolumeClaim:
            claimName: fileserver-anime-shows
        - name: anime-movies
          persistentVolumeClaim:
            claimName: fileserver-anime-movies