## Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headphones
spec:
  ingressClassName: traefik-internal
  rules:
  - host: headphones.mediaserver.k8s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  headphones
            port:
              number: 8181
              
              
## Service
---
apiVersion: v1
kind: Service
metadata:
  name: headphones
  namespace: mediaserver
  labels:
    app.kubernetes.io/name: headphones
spec:
  clusterIP: None
  ports:
  - port: 8181
  selector:
    app.kubernetes.io/name: headphones


## Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headphones
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: headphones
  serviceName: "headphones"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: headphones
    spec:
      containers:
      - name: headphones
        image: lscr.io/linuxserver/headphones:latest
        ports:
        - containerPort: 8181
          name: http-8181
        volumeMounts:
        - name: headphones-config
          mountPath: "/config"
        - name: downloads
          mountPath: "/downloads/complete"
        - name: media
          mountPath: "/media"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: headphones-config
        persistentVolumeClaim:
          claimName: headphones-config
      - name: downloads
        nfs:
          path: /mnt/pool0/downloads
          server: truenas.farhoodliquor.dmz
      - name: media
        nfs:
          path: /mnt/pool0/media
          server: truenas.farhoodliquor.dmz


---
## Volumes
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headphones-config
  namespace: mediaserver
  labels:
    name: headphones-config
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
