apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rdtclient
spec:
  ingressClassName: traefik-internal
  rules:
  - host: rdtclient.animaniacs.farh.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  rdtclient
            port:
              number: 6500
  tls:
  - hosts:
    - rdtclient.animaniacs.farh.net
    secretName: farh-net-cert-letsencrypt