---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission
spec:
  ingressClassName: traefik-internal
  rules:
  - host: transmission.animaniacs.farh.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  transmission
            port:
              number: 9091

  tls:
  - hosts:
    - transmission.animaniacs.farh.net
    secretName: farh-net-cert-letsencrypt