## Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
spec:
  ingressClassName: traefik-internal
  rules:
  - host: sonarr.mediaserver.animaniacs.k8s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  sonarr
            port:
              number: 8989
