apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
spec:
  ingressClassName: traefik-external
  rules:
  - host: sonarr.animaniacs.farh.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  sonarr
            port:
              number: 8989
  tls:
  - hosts:
    - sonarr.animaniacs.farh.net
    secretName: farh-net-cert-letsencrypt