apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  namespace: mediaserver
spec:
  rules:
  - host: streaming.farhoodliquor.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  jellyfin
            port:
              number: 8096
  - host: apps.farhoodliquor.com
    http:
      paths:
      - path: /sabnzbd/
        pathType: Prefix
        backend:
          service:
            name:  sabnzbd
            port:
              number: 8080
      - path: /sonarr/
        pathType: Prefix
        backend:
          service:
            name:  sonarr
            port:
              number: 8989
      - path: /radarr/
        pathType: Prefix
        backend:
          service:
            name:  radarr
            port:
              number: 7878
      - path: /readarr/
        pathType: Prefix
        backend:
          service:
            name:  readarr
            port:
              number: 8787
      - path: /prowlarr/
        pathType: Prefix
        backend:
          service:
            name:  prowlarr
            port:
              number: 9696

  tls:
  - hosts:
    - streaming.farhoodliquor.com
    secretName: farhoodliquor-com-cert-letsencrypt-prod
