apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tautulli
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect@kubernetescrd
spec:
  ingressClassName: traefik-external
  rules:
  - host: stats.farh.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  tautulli
            port:
              number: 8181

  tls:
  - hosts:
    - stats.farh.net
    secretName: farh-net-cert-letsencrypt

