apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mediaserver
replacements:
  - source:
      kind: ConfigMap
      name: mediaserver-config
      namespace: mediaserver
      apiVersion: v1
      fieldPath: data.FQDN
    targets:
      - path: ingress-mediaserver.yaml
        fieldPaths:
          - spec/rules/0/host
         
resources:
# Ingress
  - ingress-mediaserver.yaml
  
# Shared Volumes
  - volumes.yaml

# Monitoring
  - statefulset-tautulli.yaml
  - service-tautulli.yaml

# Media Request System
  - statefulset-overseerr.yaml
  - service-overseerr.yaml

# Media Management
# TinyMediaManager
  - service-tinymediamanager.yaml
  - statefulset-tinymediamanager.yaml
# Prowlarr Indexer Manager
  - statefulset-prowlarr.yaml
  - service-prowlarr.yaml
# AutoBRR Grabber
  - statefulset-autobrr.yaml
  - service-autobrr.yaml
# Flaresolverr Resolver
  - deployment-flaresolverr.yaml
  - service-flaresolverr.yaml
# Lidarr Media Manager
  - statefulset-lidarr.yaml
  - service-lidarr.yaml
# Sonarr Media Manager
  - statefulset-sonarr.yaml
  - service-sonarr.yaml
# Radarr Media Manager
  - statefulset-radarr.yaml
  - service-radarr.yaml
# Whisparr Media Manager
  - statefulset-whisparr.yaml
  - service-whisparr.yaml

# Downloaders
# Sabnzbd Downloader
  - statefulset-sabnzbd.yaml
  - service-sabnzbd.yaml
# RDTClient Downloader
#  - statefulset-rdtclient.yaml
#  - service-rdtclient.yaml
# Transmission Downloader
  - statefulset-transmission.yaml
  - service-transmission.yaml
  - statefulset-transmission-movies.yaml
  - service-transmission-movies.yaml

# Media Servers
#  - statefulset-plex.yaml
#  - service-plex.yaml
  - volumes-clusterplex.yaml
  - helmrepository-clusterplex.yaml
  - helmrelease-clusterplex.yaml
  - helmrepository-jellyfin.yaml
  - helmrelease-jellyfin.yaml
#  - jellyfin.yaml



