apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mediaserver
resources:

# Flux Receiver
  - receiver-cpfarhood-mediaserver.yaml

# Certificate
  - certificate.yaml

# Inrgress
  - ingress.yaml
  
# Shared Volumes
  - volumes.yaml

# Media Management
#  - service-tinymediamanager.yaml
#  - statefulset-tinymediamanager.yaml

# Prowlarr Indexer Manager
  - statefulset-prowlarr.yaml
  - service-prowlarr.yaml
  - ingress-prowlarr.yaml

# Flaresolverr Resolver
  - deployment-flaresolverr.yaml
  - service-flaresolverr.yaml

# Sonarr Media Manager
  - statefulset-sonarr.yaml
  - service-sonarr.yaml
  - ingress-sonarr.yaml

# Radarr Media Manager
  - statefulset-radarr.yaml
  - service-radarr.yaml
  - ingress-radarr.yaml

# Sabnzbd Downloader
  - statefulset-sabnzbd.yaml
  - service-sabnzbd.yaml
  - ingress-sabnzbd.yaml

# RDTClient Downloader
#  - statefulset-rdtclient.yaml
#  - service-rdtclient.yaml
#  - ingress-rdtclient.yaml

# Transmission Downloader
  - configmap-transmission-config.yaml
#  - sealedsecret-openvpn-credentials.yaml
#  - statefulset-transmission.yaml
  - service-transmission.yaml
  - ingress-transmission.yaml


#  - radarr.yaml
#  - lidarr.yaml
#  - readarr.yaml
#  - lazylibrarian.yaml
#  - headphones.yaml


# Media Servers
#  - clusterplex.yaml
  - statefulset-plex.yaml
  - service-plex.yaml
#  - statefulset-plex-livetv.yaml
#  - service-plex-livetv.yaml
#  - jellyfin.yaml

# Media Request System
#  - statefulset-overseerr.yaml
#  - service-overseerr.yaml
#  - ingress-overseerr.yaml

# Administrative
#  - tautulli.yaml
#  - ingress-tautulli.yaml
#  - autobrr.yaml

