apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mediaserver
#secretGenerator:
#- name: application-pass
#  literals:
#  - password=somepassword
resources:
  - volumes.yaml
  - service-plex.yaml
  #- service-jellyfin.yaml
  - service-prowlarr.yaml
  - service-overseerr.yaml
  - service-sonarr.yaml
  - service-radarr.yaml
  - service-lidarr.yaml
  - service-tautulli.yaml
  #- service-readarr.yaml
  - service-sabnzbd.yaml
  #- ingress.yaml
