apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mediaserver
#secretGenerator:
#- name: application-pass
#  literals:
#  - password=somepassword
resources:
  - plex.yaml
  #- jellyfin.yaml
  - prowlarr.yaml
  - overseerr.yaml
  - sonarr.yaml
  - radarr.yaml
  #- lidarr.yaml
  - tautulli.yaml
  #- readarr.yaml
  - lazylibrarian.yaml
  - headphones.yaml
  - sabnzbd.yaml
  - ingress.yaml
