apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mediaserver
resources:

# Certificate
  - certificate.yaml

# Inrgress
  - ingress.yaml
  
# Shared Volumes
  - volumes.yaml

# Media Management
#  - service-tinymediamanager.yaml
#  - statefulset-tinymediamanager.yaml

# Prowlarr Indexer Manager
  - statefulset-prowlarr.yaml
  - service-prowlarr.yaml

# Flaresolverr Resolver
  - deployment-flaresolverr.yaml
  - service-flaresolverr.yaml

# Sonarr Media Manager
  - statefulset-sonarr.yaml
  - service-sonarr.yaml

# Radarr Media Manager
  - statefulset-radarr.yaml
  - service-radarr.yaml

# Sabnzbd Downloader
  - statefulset-sabnzbd.yaml
  - service-sabnzbd.yaml

# RDTClient Downloader
#  - statefulset-rdtclient.yaml
#  - service-rdtclient.yaml

# Transmission Downloader
#  - configmap-transmission-config.yaml
#  - statefulset-transmission.yaml
#  - service-transmission.yaml

# Qbittorrent Downloader
  - configmap-qbittorrent-config.yaml
  - configmap-qbittorrent-ovpn.yaml
  - statefulset-qbittorrent.yaml
  - service-qbittorrent.yaml

# Media Servers
#  - clusterplex.yaml
#  - statefulset-plex.yaml
#  - service-plex.yaml
#  - statefulset-plex-livetv.yaml
#  - service-plex-livetv.yaml
#  - jellyfin.yaml

# Media Request System
  - statefulset-overseerr.yaml
  - service-overseerr.yaml

# Administrative
  - statefulset-tautulli.yaml
  - service-tautulli.yaml
#  - autobrr.yaml
