apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mediaserver
resources:
# Shared Volumes
  - volumes.yaml
  - sealedsecret-openvpn-credentials.yaml
  - sealedsecret-zurg-config.yaml

# Local Media Library
#  - fileserver.yaml

# Remote Media Service
  - zurg.yaml

# Indexers
  - prowlarr.yaml
#  - sonarr.yaml
#  - radarr.yaml
#  - lidarr.yaml
#  - readarr.yaml
#  - lazylibrarian.yaml
#  - headphones.yaml
#  - riven.yaml

# Downloaders
#  - sabnzbd.yaml
#  - transmission.yaml
#  - rdtclient.yaml

# Media Servers
  #- clusterplex.yaml
  - plex.yaml
  - plex-livetv.yaml
#  - jellyfin.yaml

# Administrative
  - tautulli.yaml
  - overseerr.yaml
#  - autobrr.yaml

