apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mediaserver
#secretGenerator:
#- name: application-pass
#  literals:
#  - password=somepassword
resources:
  - plex.yaml
  - tautulli.yaml
  - overseerr.yaml
  #- jellyfin.yaml
  #- autobrr.yaml
  - prowlarr.yaml
  #- sonarr.yaml
  - radarr.yaml
  - lidarr.yaml
  #- readarr.yaml
  #- lazylibrarian.yaml
  #- headphones.yaml
  - sabnzbd.yaml
  - transmission.yaml
  - sealedsecret-openvpn-credentials.yaml