apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mediaserver
       
resources:
  - configmap-mediaserver.yaml
  - ingress-mediaserver.yaml
  - volumes.yaml
  - statefulset-tautulli.yaml
  - service-tautulli.yaml
  - statefulset-overseerr.yaml
  - service-overseerr.yaml
  - service-tinymediamanager.yaml
  - statefulset-tinymediamanager.yaml
  - statefulset-prowlarr.yaml
  - service-prowlarr.yaml
  - statefulset-autobrr.yaml
  - service-autobrr.yaml
  - deployment-flaresolverr.yaml
  - service-flaresolverr.yaml
  - statefulset-lidarr.yaml
  - service-lidarr.yaml
  - statefulset-sonarr.yaml
  - service-sonarr.yaml
  - statefulset-radarr.yaml
  - service-radarr.yaml
  - statefulset-whisparr.yaml
  - service-whisparr.yaml
  - statefulset-sabnzbd.yaml
  - service-sabnzbd.yaml
  - service-transmission.yaml
  - service-transmission-movies.yaml
  - service-transmission-shows.yaml
  - statefulset-transmission.yaml
  - statefulset-transmission-movies.yaml
  - statefulset-transmission-shows.yaml
#  - service-qbittorrent-movies.yaml
#  - statefulset-qbittorrent-movies.yaml
  - volumes-clusterplex.yaml
  - helmrepository-clusterplex.yaml
  - helmrelease-clusterplex.yaml
  - helmrepository-jellyfin.yaml
  - helmrelease-jellyfin.yaml
