apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mediaserver
resources:
  #- clusterplex.yaml
  - plex.yaml
  - tautulli.yaml
  - overseerr.yaml
  #- jellyfin.yaml
  #- autobrr.yaml
  - prowlarr.yaml
  - sonarr.yaml
  - radarr.yaml
  #- lidarr.yaml
  #- readarr.yaml
  #- lazylibrarian.yaml
  #- headphones.yaml
  - sabnzbd.yaml
  - transmission.yaml
  - rdtclient-movies.yaml
  - rdtclient-shows.yaml
  - sealedsecret-openvpn-credentials.yaml