apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mediaserver
resources:
# Shared Volumes
  - volumes.yaml
  - sealedsecret-openvpn-credentials.yaml
#  - sealedsecret-zurg-config.yaml

# Media Management
  - tinymediamanager.yaml

# Prowlarr Indexer Manager
  - prowlarr.yaml

# Sonarr Media Manager
  - statefulset-sonarr.yaml
  - service-sonarr.yaml
  - ingress-sonarr.yaml

# Sabnzbd Downloader
  - statefulset-sabnzbd.yaml
  - service-sabnzbd.yaml
  - ingress-sabnzbd.yaml
  
#  - radarr.yaml
#  - lidarr.yaml
#  - readarr.yaml
#  - lazylibrarian.yaml
#  - headphones.yaml

# Downloaders
#  - transmission.yaml
#  - rdtclient.yaml

# Media Servers
#  - clusterplex.yaml
  - plex.yaml
  - plex-livetv.yaml
#  - jellyfin.yaml

# Administrative
  - tautulli.yaml
  - ingress-tautulli.yaml
  - overseerr.yaml
#  - autobrr.yaml

