apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mediaserver
resources:
  - volumes.yaml
  #- clusterplex.yaml
  - plex.yaml
  - plex-shows.yaml
  - tautulli.yaml
#  - overseerr.yaml
#  - jellyfin.yaml
#  - autobrr.yaml
  - prowlarr.yaml
  - sonarr.yaml
  - radarr.yaml
#  - lidarr.yaml
#  - readarr.yaml
#  - lazylibrarian.yaml
#  - headphones.yaml
  - sabnzbd.yaml
  - transmission.yaml
  - rdtclient.yaml
  - zurg.yaml
  - sealedsecret-openvpn-credentials.yaml
  - sealedsecret-zurg-config.yaml
  - riven.yaml