apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mediaserver
resources:

# Ingress
  - ingress-mediaserver.yaml
  
# Shared Volumes
  - volumes.yaml

# Monitoring
  - statefulset-tautulli.yaml
  - service-tautulli.yaml

# Media Request System
  - statefulset-overseerr.yaml
  - service-overseerr.yaml

# Media Management
# TinyMediaManager
  - service-tinymediamanager.yaml
  - statefulset-tinymediamanager.yaml
# Prowlarr Indexer Manager
  - statefulset-prowlarr.yaml
  - service-prowlarr.yaml
# AutoBRR Grabber
  - statefulset-autobrr.yaml
  - service-autobrr.yaml
# Flaresolverr Resolver
  - deployment-flaresolverr.yaml
  - service-flaresolverr.yaml
# Lidarr Media Manager
  - statefulset-lidarr.yaml
  - service-lidarr.yaml
# Sonarr Media Manager
  - statefulset-sonarr.yaml
  - service-sonarr.yaml
# Radarr Media Manager
  - statefulset-radarr.yaml
  - service-radarr.yaml
# Whisparr Media Manager
  - statefulset-whisparr.yaml
  - service-whisparr.yaml

# Downloaders
# Sabnzbd Downloader
  - statefulset-sabnzbd.yaml
  - service-sabnzbd.yaml
# RDTClient Downloader
#  - statefulset-rdtclient.yaml
#  - service-rdtclient.yaml
# Transmission Downloader
  - configmap-transmission-config.yaml
  - statefulset-transmission.yaml
  - service-transmission.yaml
# Qbittorrent Downloader
#  - configmap-qbittorrent-config.yaml
#  - configmap-qbittorrent-ovpn.yaml
#  - statefulset-qbittorrent.yaml
#  - service-qbittorrent.yaml

# Media Servers
#  - statefulset-plex.yaml
#  - service-plex.yaml
  - configmap-clusterplex-values.yaml
  - volumes-clusterplex.yaml
  - helmrepository-clusterplex.yaml
  - helmrelease-clusterplex.yaml
  - configmap-jellyfin-values.yaml
  - volumes-jellyfin.yaml
  - helmrepository-jellyfin.yaml
  - helmrelease-jellyfin.yaml
#  - jellyfin.yaml



