## Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lazylibrarian
  namespace: mediaserver
spec:
  ingressClassName: traefik-internal
  rules:
  - host: lazylibrarian.mediaserver.k8s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  lazylibrarian
            port:
              number: 5299
              
              
## Service
---
apiVersion: v1
kind: Service
metadata:
  name: lazylibrarian
  namespace: mediaserver
  labels:
    app: lazylibrarian
spec:
  clusterIP: None
  ports:
  - port: 5299
  selector:
    app: lazylibrarian


## Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lazylibrarian
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: lazylibrarian
  serviceName: "lazylibrarian"
  replicas: 1
  template:
    metadata:
      labels:
        app: lazylibrarian
    spec:
      containers:
      - name: lazylibrarian
        image: lscr.io/linuxserver/lazylibrarian:latest
        ports:
        - containerPort: 5299
          name: http-5299
        volumeMounts:
        - name: lazylibrarian-config
          mountPath: "/config"
        - name: downloads
          mountPath: "/downloads"
        - name: media
          mountPath: "/media"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: lazylibrarian-config
        persistentVolumeClaim:
          claimName: lazylibrarian-config
      - name: downloads
        nfs:
          path: /mnt/pool0/downloads
          server: truenas.farhoodliquor.dmz
      - name: media
        nfs:
          path: /mnt/pool0/media
          server: truenas.farhoodliquor.dmz


## Volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lazylibrarian-config
  namespace: mediaserver
  labels:
    name: lazylibrarian-config
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
      