## Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lazylibrarian
  namespace: mediaserver
spec:
  ingressClassName: traefik-internal
  rules:
  - host: lazylibrarian.mediaserver.k8s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  lazylibrarian
            port:
              number: 5299
              
              
## Service
---
apiVersion: v1
kind: Service
metadata:
  name: lazylibrarian
  namespace: mediaserver
  labels:
    app: lazylibrarian
spec:
  clusterIP: None
  ports:
  - port: 5299
  selector:
    app: lazylibrarian


## StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lazylibrarian
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: lazylibrarian
  serviceName: "lazylibrarian"
  replicas: 1
  template:
    metadata:
      labels:
        app: lazylibrarian
    spec:
      containers:
      - name: lazylibrarian
        image: lscr.io/linuxserver/lazylibrarian:latest
        ports:
        - containerPort: 5299
          name: http-5299
        volumeMounts:
        - name: lazylibrarian-config
          mountPath: "/config"
        - name: lazylibrarian-downloads
          mountPath: "/downloads"
        - name: lazylibrarian-content
          mountPath: "/media"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: lazylibrarian-config
        persistentVolumeClaim:
          claimName: lazylibrarian-config
  volumeClaimTemplates:
  - metadata:
      name: lazylibrarian-downloads
    spec:
      volumeName: lazylibrarian-downloads
      accessModes: ["ReadWriteMany"]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: lazylibrarian-content
    spec:
      volumeName: lazylibrarian-content
      accessModes: ["ReadWriteMany"]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 1Gi


## Volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lazylibrarian-config
  namespace: mediaserver
  labels:
    name: lazylibrarian-config
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lazylibrarian-downloads
  labels:
    name: lazylibrarian-downloads
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/downloads/
    server: spielberg.farhoodliquor.dmz
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lazylibrarian-content
  labels:
    name: lazylibrarian-content
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/media/
    server: spielberg.farhoodliquor.dmz