## Service
---
apiVersion: v1
kind: Service
metadata:
   name: plex-livetv
   namespace: mediaserver
   labels:
     app: plex-livetv
   annotations:
     metallb.universe.tf/loadBalancerIPs: 65.43.40.106
spec:
  selector:
    app: plex-livetv
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 443
    targetPort: 32400
    name: http-32400
---


## StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex-livetv
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: plex-livetv
  serviceName: "plex-livetv"
  replicas: 0
  template:
    metadata:
      labels:
        app: plex-livetv
    spec:
      containers:
      - name: plex
        image: docker.io/plexinc/pms-docker:plexpass
        imagePullPolicy: Always
        ports:
        - containerPort: 32400
          name: http-32400
        env:
        - name: TZ
          value: America/Detroit
        - name: VERSION
          value: docker
        - name: PLEX_UID
          value: "911"
        - name: PLEX_GID
          value: "911"
        - name: PLEX_CLAIM
          value: claim-s5ze8dETkas9PNJ9YkPk
        - name: ADVERITSE_IP
          value: https://65.43.40.106
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: transcode
          mountPath: "/transcode"
        - name: recordings
          mountPath: "/media/local/recordings"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            gpu.intel.com/i915: 1
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: plex-livetv-config
      - name: transcode
        emptyDir: 
          sizeLimit: 128Gi
      - name: recordings
        persistentVolumeClaim:
          claimName: mediaserver-recordings
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"


## Volume Claims
---
