## Service
---
apiVersion: v1
kind: Service
metadata:
   name: plex
   namespace: mediaserver
   labels:
     app: plex
   annotations:
     metallb.universe.tf/loadBalancerIPs: 65.43.40.107
spec:
  selector:
    app: plex
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 443
    targetPort: 32400
    name: http-32400
---


## StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: plex
  serviceName: "plex"
  replicas: 1
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: docker.io/plexinc/pms-docker:plexpass
        imagePullPolicy: Always
        ports:
        - containerPort: 32400
          name: http-32400
        env:
        - name: TZ
          value: America/Detroit
        - name: VERSION
          value: docker
        - name: PLEX_UID
          value: "911"
        - name: PLEX_GID
          value: "911"
        - name: PLEX_CLAIM
          value: claim-sLPQHyQbVe5g8yGv4Nf-
#        - name: ADVERITSE_IP
#          value: https://0.0.0.0:32400
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: remote
          mountPath: "/media/remote"
        - name: local
          mountPath: "/media/local"
        - name: transcode
          mountPath: "/transcode"
        resources:
          requests:
            memory: "2Gi"
            cpu: "2000m"
          limits:
            gpu.intel.com/i915: 1
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: plex-config
      - name: transcode
        emptyDir: 
          sizeLimit: 128Gi
      - name: local
        nfs:
          path: /exports
          server: fileserver.mediaserver.k8s
      - name: remote
        persistentVolumeClaim:
          claimName: mediaserver-remote
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"
