## Ingress - this will hide the true source ip for clients because Plex doesn't implement ProxyProtocol
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: plex
#  namespace: mediaserver
#  annotations:
#    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect@kubernetescrd
#spec:
#  ingressClassName: traefik-external
#  rules:
#  - host: streaming.farhoodliquor.com
#    http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name:  plex
#            port:
#              number: 32400
#  tls:
#  - hosts:
#    - streaming.farhoodliquor.com
#    secretName: farhoodliquor-com-cert-letsencrypt-prod
    
    
## Service
---
apiVersion: v1
kind: Service
metadata:
   name: plex
   namespace: mediaserver
   labels:
     app: plex
   annotations:
     metallb.universe.tf/loadBalancerIPs: 65.43.40.99
     external-dns.alpha.kubernetes.io/hostname: streaming.farhoodliquor.com
spec:
  selector:
    app: plex
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 443
    targetPort: 32400
    name: http-32400
##


## Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: plex
  serviceName: "plex"
  replicas: 1
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: docker.io/plexinc/pms-docker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 32400
          name: http-32400
        env:
        - name: TZ
          value: America/Detroit
        - name: VERSION
          value: docker
#        - name: PLEX_CLAIM
#          value: claim-claim-token #optional
#        - name: ADVERITSE_IP
#          value: https://0.0.0.0:32400
        volumeMounts:
        - name: plex-config
          mountPath: "/config"
        - name: media
          mountPath: "/media"
        - name: plex-transcode
          mountPath: "/transcode"
        resources:
          requests:
            memory: "2Gi"
            cpu: "2000m"
          limits:
            gpu.intel.com/i915: 1
      volumes:
      - name: plex-config
        persistentVolumeClaim:
          claimName: plex-config
      - name: plex-transcode
        persistentVolumeClaim:
          claimName: plex-transcode
      - name: media
        nfs:
          path: /mnt/pool0/media
          server: spielberg.farhoodliquor.dmz
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"


## Volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: mediaserver
  labels:
    name: plex-config
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: rook-ceph-block-nvme
  resources:
    requests:
      storage: 128Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-transcode
  namespace: mediaserver
  labels:
    name: plex-transcode
  annotations:
    kustomize.toolkit.fluxcd.io/prune: enabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: rook-ceph-block-nvme
  resources:
    requests:
      storage: 256Gi
    