## Service
---
apiVersion: v1
kind: Service
metadata:
   name: plex
   namespace: mediaserver
   labels:
     app: plex
   annotations:
     metallb.universe.tf/loadBalancerIPs: 65.43.40.99
     external-dns.alpha.kubernetes.io/hostname: ota.mediaserver.farhoodliquor.com
spec:
  selector:
    app: plex
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 443
    targetPort: 32400
    name: http-32400
##


## StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: plex
  serviceName: "plex"
  replicas: 1
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: docker.io/plexinc/pms-docker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 32400
          name: http-32400
        env:
        - name: TZ
          value: America/Detroit
        - name: VERSION
          value: docker
#        - name: PLEX_CLAIM
#          value: claim-claim-token #optional
#        - name: ADVERITSE_IP
#          value: https://0.0.0.0:32400
        volumeMounts:
        - name: plex-config
          mountPath: "/config"
        - name: media
          mountPath: "/media"
        - name: plex-transcode
          mountPath: "/transcode"
        - name: temp
          mountPath: /temp
        resources:
          requests:
            memory: "2Gi"
            cpu: "2000m"
          limits:
            gpu.intel.com/i915: 1
      volumes:
      - name: plex-config
        persistentVolumeClaim:
          claimName: plex-config
      - name: plex-transcode
        persistentVolumeClaim:
          claimName: plex-transcode
      - name: temp
        nfs:
          server: spielberg.farhoodliquor.dmz
          path: /mnt/pool0/backups/temp
      - name: media
        nfs:
          path: /mnt/pool0/media
          server: spielberg.farhoodliquor.dmz
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"


## Volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: mediaserver
  labels:
    name: plex-config
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-perpetual
  resources:
    requests:
      storage: 128Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-transcode
  namespace: mediaserver
  labels:
    name: plex-transcode
    kustomize.toolkit.fluxcd.io/prune: enabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-ephemeral
  resources:
    requests:
      storage: 256Gi
    