## Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr
  namespace: mediaserver
spec:
  ingressClassName: traefik-internal
  rules:
  - host: prowlarr.mediaserver.k8s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  prowlarr
            port:
              number: 9696
              
              
## Service
---
apiVersion: v1
kind: Service
metadata:
   name: prowlarr
   namespace: mediaserver
   labels:
     app: prowlarr
spec:
  clusterIP: None
  ports:
  - port: 9696
  selector:
    app: prowlarr


## Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: prowlarr
  serviceName: "prowlarr"
  replicas: 1
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
      - name: prowlarr
        image: lscr.io/linuxserver/prowlarr:latest
        ports:
        - containerPort: 9696
          name: http-9696
        volumeMounts:
        - name: prowlarr-config
          mountPath: "/config"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: prowlarr-config
        persistentVolumeClaim:
          claimName: prowlarr-config


## Volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: mediaserver
  labels:
    name: prowlarr-config
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: rook-ceph-block-nvme
  resources:
    requests:
      storage: 8Gi