## This is an indexing service for torrents and nzbs

## Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr
  namespace: mediaserver
spec:
  ingressClassName: traefik-internal
  rules:
  - host: prowlarr.mediaserver.k8s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  prowlarr
            port:
              number: 9696
              
              
## Service
---
apiVersion: v1
kind: Service
metadata:
   name: prowlarr
   namespace: mediaserver
   labels:
     app.kubernetes.io/name: prowlarr
spec:
  type: ClusterIP
  #clusterIP: None
  ports:
  - port: 9696
  selector:
    app.kubernetes.io/name: prowlarr


## StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prowlarr
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prowlarr
  serviceName: "prowlarr"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prowlarr
    spec:
      containers:
      - name: prowlarr
        image: lscr.io/linuxserver/prowlarr:latest
        ports:
        - name: prowlarr-http
          containerPort: 9696
        volumeMounts:
        - name: prowlarr-config
          mountPath: "/config"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        readinessProbe:                # Check that the http server is responding to ensure the container is up
          httpGet:
            path: /
            port: prowlarr-http
        livelinessProbe:               # Check that the http server is responding to ensure the container is up
          httpGet:
            path: /
            port: prowlarr-http
            failureThreshold: 5
      volumes:
      - name: prowlarr-config
        persistentVolumeClaim:
          claimName: prowlarr-config
