## Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rdtclient
  namespace: mediaserver
spec:
  ingressClassName: traefik-internal
  rules:
  - host: rdtclient.mediaserver.k8s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  rdtclient
            port:
              number: 6500
              
          
## Service
---
apiVersion: v1
kind: Service
metadata:
  name: rdtclient
  namespace: mediaserver
  labels:
    app: rdtclient
spec:
  clusterIP: None
  ports:
  - port: 6500
    targetPort: 6500
    name: rdtclient
  selector:
    app: rdtclient


## StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rdtclient
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: rdtclient
  serviceName: "rdtclient"
  replicas: 1
  template:
    metadata:
      labels:
        app: rdtclient
    spec:
      containers:
      - name: rdtclient
        image: rogerfar/rdtclient:latest
        ports:
        - containerPort: 6500
          name: http-6500
        volumeMounts:
        - name: rdtclient-db
          mountPath: "/data/db"
        - name: library
          mountPath: /media/library
        - name: rdtclient-remotemedia
          mountPath: "/media/remote"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: rdtclient-db
        persistentVolumeClaim:
          claimName: rdtclient-db
        - name: library
          nfs:
            path: /mnt/pool0/media/library
            server: spielberg.farhoodliquor.dmz
      - name: rdtclient-remotemedia
        persistentVolumeClaim:
          claimName: rdtclient-remotemedia


## Volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rdtclient-db
  namespace: mediaserver
  labels:
    name: rdtclient-db
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-perpetual
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rdtclient-remotemedia
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rclone
  selector:
    matchLabels:
      name: rdtclient-farhoodliquor-remotemedia
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rdtclient-farhoodliquor-remotemedia-pv
  labels:
    name: rdtclient-farhoodliquor-remotemedia
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  storageClassName: rclone
  csi:
    driver: csi-rclone
    volumeHandle: data-id
    volumeAttributes:
      remote: "http"
      remotePath: "/http/"
      http-url: "http://zurg.mediaserver.k8s/http/"