## Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sabnzbd
  namespace: mediaserver
spec:
  ingressClassName: traefik-internal
  rules:
  - host: sabnzbd.mediaserver.k8s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  sabnzbd
            port:
              number: 8080


## Service
---
apiVersion: v1
kind: Service
metadata:
   name: sabnzbd
   namespace: mediaserver
   labels:
     app: sabnzbd
spec:
  clusterIP: None
  ports:
  - port: 8080
  selector:
    app: sabnzbd


## Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: sabnzbd
  serviceName: "sabnzbd"
  replicas: 0
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
      - name: sabnzbd
        image: lscr.io/linuxserver/sabnzbd:latest
        ports:
        - containerPort: 8080
          name: http-8080
        volumeMounts:
        - name: sabnzbd-config
          mountPath: "/config"
        - name: sabnzbd-downloads
          mountPath: "/downloads/sabnzbd-incomplete"
        - name: sabnzbd-backups
          mountPath: "/downloads/backups"
        - name: downloads
          mountPath: "/downloads/complete"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: sabnzbd-config
        persistentVolumeClaim:
          claimName: sabnzbd-config
      - name: sabnzbd-backups
        persistentVolumeClaim:
          claimName: sabnzbd-backups
      - name: sabnzbd-downloads
        persistentVolumeClaim:
          claimName: sabnzbd-downloads
      - name: downloads
        nfs:
          path: /mnt/pool0/downloads
          server: spielberg.farhoodliquor.dmz


## Volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config
  labels:
    name: sabnzbd-config
  namespace: mediaserver
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-backups
  labels:
    name: sabnzbd-backups
  namespace: mediaserver
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 32Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-downloads
  labels:
    name: sabnzbd-downloads
  namespace: mediaserver
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 256Gi