---
apiVersion: v1
kind: Service
metadata:
   name: lidarr
   namespace: mediaserver
   labels:
     app: lidarr
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 8686
    name: http-8686
  selector:
    app: lidarr
--- 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lidarr
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: lidarr
  serviceName: "lidarr"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      containers:
      - name: lidarr
        image: lscr.io/linuxserver/lidarr:latest
        ports:
        - containerPort: 8686
          name: http-8686
        volumeMounts:
        - name: lidarr-config
          mountPath: "/config"
        - name: lidarr-downloads
          mountPath: "/downloads"
        - name: lidarr-content
          mountPath: "/media"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: lidarr-config
        persistentVolumeClaim:
          claimName: lidarr-config
  volumeClaimTemplates:
  - metadata:
      name: lidarr-downloads
    spec:
      volumeName: lidarr-downloads
      accessModes: ["ReadWriteMany"]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: lidarr-content
    spec:
      volumeName: lidarr-content
      accessModes: ["ReadWriteMany"]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 1Gi
