## Service
---
apiVersion: v1
kind: Service
metadata:
   name: radarr
   labels:
     app.kubernetes.io/name: radarr
spec:
  type: ClusterIP
  #clusterIP: None
  ports:
  - port: 7878
  selector:
    app.kubernetes.io/name: radarr
