## Service
---
apiVersion: v1
kind: Service
metadata:
   name: sonarr
   namespace: mediaserver
   labels:
     app.kubernetes.io/name: sonarr
spec:
  type: ClusterIP
  #clusterIP: None
  ports:
  - port: 8989
  selector:
    app.kubernetes.io/name: sonarr

