## Service
---
apiVersion: v1
kind: Service
metadata:
   name: overseerr
   labels:
     app.kubernetes.io/name: overseerr
spec:
  type: ClusterIP
  ports:
  - port: 5055
  selector:
    app.kubernetes.io/name: overseerr
