---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: overseerr-ingress
  namespace: mediaserver
spec:
  rules:
  - host: streaming.farhoodliquor.com
    http:
      paths:
      - path: /requests/
        pathType: Prefix
        backend:
          service:
            name:  overseerr
            port:
              number: 5055
---
apiVersion: v1
kind: Service
metadata:
   name: overseerr
   namespace: mediaserver
   labels:
     app: overseerr
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 5055
    name: http-5055
  selector:
    app: overseerr
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: overseerr
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: overseerr
  serviceName: "overseerr"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: overseerr
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: overseer
        image: lscr.io/linuxserver/overseerr:latest
        ports:
        - containerPort: 5055
          name: http-5055
        volumeMounts:
        - name: overseerr-config
          mountPath: "/config"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: overseerr-config
        persistentVolumeClaim:
          claimName: overseerr-config
