---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: mediaserver
  labels:
    app: jellyfin
  annotations:
    traefik.ingress.kubernetes.io/service.nativelb: "true"
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8096
  selector:
    app: jellyfin
  type: LoadBalancer
  externalTrafficPolicy: Local
---
kind: Service
apiVersion: v1
metadata:
  name: jellyfin-external  
spec:
  type: ExternalName
  ports:
  - name: http    
    port: 80   
  externalName: streaming.farhoodliquor.com
--- 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jellyfin
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: jellyfin
  serviceName: "jellyfin"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: jellyfin
        image: docker.io/jellyfin/jellyfin:latest
        ports:
        - containerPort: 8096
          name: http-8096
        env:
        - name: TZ
          value: America/Detroit
        - name: JELLYFIN_DATA_DIR
          value: /config/data 
        - name: JELLYFIN_CONFIG_DIR
          value: /config 
        - name: JELLYFIN_LOG_DIR
          value: /config/log 
        - name: JELLYFIN_CACHE_DIR
          value: /config/cache
        volumeMounts:
        - name: jellyfin-config
          mountPath: "/config"
        - name: jellyfin-content
          mountPath: "/media"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            gpu.intel.com/i915: 1
      volumes:
      - name: jellyfin-config
        persistentVolumeClaim:
          claimName: jellyfin-config
  volumeClaimTemplates:
  - metadata:
      name: jellyfin-content
    spec:
      volumeName: jellyfin-content
      accessModes: ["ReadWriteMany"]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 1Gi
