## Service
---
apiVersion: v1
kind: Service
metadata:
   name: tinymediamanager
   labels:
     app.kubernetes.io/name: tinymediamanager
spec:
  type: ClusterIP
  ports:
  - port: 4000
  selector:
    app.kubernetes.io/name: tinymediamanager
