apiVersion: v1
kind: Service
metadata:
  name: transmission
spec:
  selector:
    app.kubernetes.io/name:  transmission
  ports:
  - port: 9091
  sessionAffinity: None
  type: ClusterIP
  #clusterIP: None