---
apiVersion: v1
kind: Service
metadata:
   name: prowlarr
   namespace: mediaserver
   labels:
     app: prowlarr
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 9696
    name: http-9696
  selector:
    app: prowlarr
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prowlarr
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: prowlarr
  serviceName: "prowlarr"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: prowlarr
        image: lscr.io/linuxserver/prowlarr:latest
        ports:
        - containerPort: 9696
          name: http-9696
        volumeMounts:
        - name: prowlarr-config
          mountPath: "/config"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: prowlarr-config
        persistentVolumeClaim:
          claimName: prowlarr-config
