apiVersion: v1
kind: Service
metadata:
  name: transmission
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "transmission.animaniacs.farh.net"
spec:
  selector:
    app.kubernetes.io/name:  transmission
  ports:
  - port: 9091
  sessionAffinity: None
  type: LoadBalancer
  externalTrafficPolicy: Local