## Service
---
apiVersion: v1
kind: Service
metadata:
  name: tinymediamanager
  labels:
    app.kubernetes.io/name: tinymediamanager
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "tinymediamanager.animaniacs.farh.net"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 4000
  selector:
    app.kubernetes.io/name: tinymediamanager
