---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: mediaserver
  labels:
    app: jellyfin
  annotations:
#    metallb.universe.tf/loadBalancerIPs: 65.43.40.98
#    external-dns.alpha.kubernetes.io/hostname: streaming.farhoodliquor.com.
    traefik.ingress.kubernetes.io/service.nativelb: "true"
spec:
  ports:
  - name: http-8096
    port: 8096
    targetPort: 8096
  selector:
    app: jellyfin
#  type: LoadBalancer
#  externalTrafficPolicy: Local
  clusterIP: None
--- 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jellyfin
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: jellyfin
  serviceName: "jellyfin"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: jellyfin
        image: docker.io/jellyfin/jellyfin:latest
        ports:
        - containerPort: 8096
          name: http-8096
        env:
        - name: TZ
          value: America/Detroit
        - name: JELLYFIN_DATA_DIR
          value: /config/data 
        - name: JELLYFIN_CONFIG_DIR
          value: /config 
        - name: JELLYFIN_LOG_DIR
          value: /config/log 
        - name: JELLYFIN_CACHE_DIR
          value: /config/cache
        volumeMounts:
        - name: jellyfin-config
          mountPath: "/config"
        - name: jellyfin-content
          mountPath: "/media"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            gpu.intel.com/i915: 1
  volumeClaimTemplates:
  - metadata:
      name: jellyfin-config
    spec:
      volumeName: jellyfin-config
      accessModes: ["ReadWriteMany"]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: jellyfin-content
    spec:
      volumeName: jellyfin-content
      accessModes: ["ReadWriteMany"]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 1Gi
