---
apiVersion: v1
kind: Service
metadata:
   name: sonarr
   namespace: mediaserver
   labels:
     app: sonarr
spec:
  clusterIP: None
  ports:
  - port: 8989
    targetPort: 8989
    name: http-8989
  selector:
    app: sonarr
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarr
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: sonarr
  serviceName: "sonarr"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/sonarr:latest
        ports:
        - containerPort: 8989
          name: http-8989
        volumeMounts:
        - name: sonarr-config
          mountPath: "/config"
        - name: sonarr-downloads
          mountPath: "/downloads"
        - name: sonarr-content
          mountPath: "/media"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: sonarr-config
        persistentVolumeClaim:
          claimName: sonarr-config
  volumeClaimTemplates:
  - metadata:
      name: sonarr-downloads
    spec:
      volumeName: sonarr-downloads
      accessModes: ["ReadWriteMany"]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: sonarr-content
    spec:
      volumeName: sonarr-content
      accessModes: ["ReadWriteMany"]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 1Gi
