## Service
---
apiVersion: v1
kind: Service
metadata:
   name: whisparr
   labels:
     app.kubernetes.io/name: whisparr
spec:
  type: ClusterIP
  #clusterIP: None
  ports:
  - port: 6969
  selector:
    app.kubernetes.io/name: whisparr
    