apiVersion: v1
kind: Service
metadata:
   name: tautulli
   labels:
     app.kubernetes.io/name: tautulli
spec:
  clusterIP: None
  ports:
  - port: 8181
  selector:
    app.kubernetes.io/name: tautulli
