---
apiVersion: v1
kind: Service
metadata:
   name: plex
   namespace: mediaserver
   labels:
     app: plex
   annotations:
     metallb.universe.tf/loadBalancerIPs: 65.43.40.99
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 443
    targetPort: 32400
    name: http-32400
  selector:
    app: plex
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: plex
  serviceName: "plex"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: docker.io/plexinc/pms-docker:latest
        ports:
        - containerPort: 32400
          name: http-32400
        env:
        - name: TZ
          value: America/Detroit
        - name: VERSION
          value: docker
#        - name: PLEX_CLAIM
#          value: claim-claim-token #optional
#        - name: ADVERITSE_IP
#          value: https://0.0.0.0:32400
        volumeMounts:
        - name: plex-config
          mountPath: "/config"
        - name: plex-content
          mountPath: "/media"
        - name: plex-transcode
          mountPath: "/transcode"
        - name: certificates
          mountPath: "/certificates"
        resources:
          requests:
            memory: "2Gi"
            cpu: "2000m"
          limits:
            gpu.intel.com/i915: 1
      volumes:
      - name: plex-config
        persistentVolumeClaim:
          claimName: plex-config
      - name: plex-transcode
        persistentVolumeClaim:
          claimName: plex-transcode
      - name: certificates
        secret:
          secretName: farhoodliquor-com-cert-letsencrypt-prod
          optional: true
      nodeSelector:
        hevc10: "true"
  volumeClaimTemplates:
  - metadata:
      name: plex-content
    spec:
      volumeName: plex-content
      accessModes: ["ReadWriteMany"]
      storageClassName: nfs
      resources:
        requests:
          storage: 1Gi
