## Service
---
apiVersion: v1
kind: Service
metadata:
   name: headphones
   labels:
     app.kubernetes.io/name: headphones
spec:
  type: ClusterIP
  #clusterIP: None
  ports:
  - port: 8181
  selector:
    app.kubernetes.io/name: headphones
    