## Service
---
apiVersion: v1
kind: Service
metadata:
   name: qbittorrent
   labels:
     app.kubernetes.io/name: qbittorrent
spec:
  type: ClusterIP
  #clusterIP: None
  ports:
  - port: 8080
  selector:
    app.kubernetes.io/name: qbittorrent
    