## Service
#apiVersion: v1
#kind: Service
#metadata:
#   name: sabnzbd
#   labels:
#     app.kubernetes.io/name: sabnzbd
#spec:
#  type: ClusterIP
#  ports:
#  - port: 8080
#  selector:
#    app.kubernetes.io/name: sabnzbd


## Headless Service
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  labels:
    app.kubernetes.io/name: sabnzbd
spec:
  clusterIP: None  # Makes it a headless service
  ports:
    - port: 8080
  selector:
    app.kubernetes.io/name: sabnzbd