apiVersion: v1
kind: Service
metadata:
   name: autobrr
   namespace: mediaserver
   labels:
     app.kubernetes.io/name: autobrr
spec:
  type: ClusterIP
  #clusterIP: None
  ports:
  - port: 7474
  selector:
    app.kubernetes.io/name: autobrr
