## Service
---
apiVersion: v1
kind: Service
metadata:
   name: rdtclient
   namespace: mediaserver
   labels:
     app.kubernetes.io/name: rdtclient
spec:
  type: ClusterIP
  ports:
  - port: 6500
  selector:
    app.kubernetes.io/name: rdtclient
