apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: mediaserver
  labels:
    app.kubernetes.io/name: plex
    zone: public
  annotations:
    lbipam.cilium.io/ips: "65.43.40.102"
spec:
  selector:
    app.kubernetes.io/name: plex
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 443
    targetPort: 32400
    name: http-32400