---
apiVersion: v1
kind: Service
metadata:
   name: readarr
   labels:
     app: readarr
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 7878
    name: http-7878
  selector:
    app: readarr
--- # service
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: readarr
spec:
  selector:
    matchLabels:
      app: readarr
  serviceName: "readarr"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: readarr
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/readarr:latest
        ports:
        - containerPort: 7878
          name: http-7878
        volumeMounts:
        - name: readarr-config
          mountPath: "/config"
        - name: readarr-downloads
          mountPath: "/downloads"
        - name: readarr-content
          mountPath: "/media"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: readarr-config
        persistentVolumeClaim:
          claimName: readarr-config
  volumeClaimTemplates:
  - metadata:
      name: readarr-downloads
    spec:
      volumeName: readarr-downloads
      accessModes: ["ReadWriteMany"]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: readarr-content
    spec:
      volumeName: readarr-content
      accessModes: ["ReadWriteMany"]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 1Gi
