## Service
---
apiVersion: v1
kind: Service
metadata:
   name: sabnzbd
   namespace: mediaserver
   labels:
     app.kubernetes.io/name: sabnzbd
spec:
  type: ClusterIP
  #clusterIP: None
  ports:
  - port: 8080
  selector:
    app.kubernetes.io/name: sabnzbd
