---
apiVersion: v1
kind: Service
metadata:
   name: plex
   namespace: mediaserver
   labels:
     app: plex
#   annotations:
#     metallb.universe.tf/loadBalancerIPs: 65.43.40.99
#     external-dns.alpha.kubernetes.io/hostname: plex.farhoodliquor.com.
spec:
  clusterIP: None
#  type: LoadBalancer
#  externalTrafficPolicy: Local
  ports:
  - port: 32400
    targetPort: 32400
    name: http-32400
  selector:
    app: plex
--- # service
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: plex
  serviceName: "plex"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: plex
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: plex
        image: lscr.io/linuxserver/plex:latest
        ports:
        - containerPort: 32400
          name: http-32400
        env:
        - name: TZ
          value: America/Detroit
        - name: VERSION
          value: docker
        - name: PLEX_CLAIM
          value: claim-GT-txeEDnG_NhoCpNxpp #optional
        - name: ADVERITSE_IP
          value: https://65.43.40.99:32400
        volumeMounts:
        - name: plex-config
          mountPath: "/config"
        - name: plex-content
          mountPath: "/media"
        - name: certificates
          readOnly: true
          mountPath: "/certificates"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            gpu.intel.com/i915: 1
      volumes:
      - name: plex-config
        persistentVolumeClaim:
          claimName: plex-config
      - name: certificates
        secret:
          secretName: farhoodliquor-com-cert-letsencrypt-prod
  volumeClaimTemplates:
  - metadata:
      name: plex-content
    spec:
      volumeName: plex-content
      accessModes: ["ReadWriteMany"]
      storageClassName: nfs
      resources:
        requests:
          storage: 1Gi
