---
apiVersion: v1
kind: Service
metadata:
   name: jellyfin
   labels:
     app: jellyfin
spec:
  ports:
    - port: 8096
  selector:
    app: jellyfin
  clusterIP: None
--- 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin
  serviceName: "jellyfin"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: jellyfin
        image: docker.io/jellyfin/jellyfin:latest
        ports:
        - containerPort: 8096
          name: http-8096
        env:
        - name: TZ
          value: America/Detroit
        volumeMounts:
        - name: jellyfin-config
          mountPath: "/config"
        - name: jellyfin-cert
          mountPath: "/certificate"
        - name: jellyfin-content
          mountPath: "/media"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: jellyfin-config
        persistentVolumeClaim:
          claimName: jellyfin-config
      - name: jellyfin-cert
        secret:
          secretName: farhoodliquor-com-cert-letsencrypt-prod
  volumeClaimTemplates:
  - metadata:
      name: jellyfin-content
    spec:
      volumeName: jellyfin-content
      accessModes: ["ReadWriteMany"]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 1Gi
