---
apiVersion: v1
kind: Service
metadata:
   name: sabnzbd
   labels:
     app: sabnzbd
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    name: http-8080
  selector:
    app: sabnzbd
--- # service
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sabnzbd 
spec:
  selector:
    matchLabels:
      app: sabnzbd
  serviceName: "sabnzbd"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: sabnzbd
        image: lscr.io/linuxserver/sabnzbd:latest
        ports:
        - containerPort: 8080
          name: http-8080
        volumeMounts:
        - name: sabnzbd-config
          mountPath: "/config"
        - name: sabnzbd-downloads
          mountPath: "/downloads"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: sabnzbd-config
        persistentVolumeClaim:
          claimName: sabnzbd-config
  volumeClaimTemplates:
  - metadata:
      name: sabnzbd-downloads
    spec:
      volumeName: sabnzbd-downloads
      accessModes: ["ReadWriteMany"]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 1Gi