---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-ingress
  namespace: mediaserver
spec:
  rules:
  - host: plex.farhoodliquor.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  plex
            port:
              number: 32400
  tls:
  - hosts:
    - plex.farhoodliquor.com
    secretName: farhoodliquor-com-cert-letsencrypt-prod
---
apiVersion: v1
kind: Service
metadata:
   name: plex
   namespace: mediaserver
   labels:
     app: plex
spec:
  clusterIP: None
  ports:
  - port: 32400
    targetPort: 32400
    name: http-32400
  selector:
    app: plex
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: plex
  serviceName: "plex"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: lscr.io/linuxserver/plex:latest
        ports:
        - containerPort: 32400
          name: http-32400
        env:
        - name: TZ
          value: America/Detroit
        - name: VERSION
          value: docker
#        - name: PLEX_CLAIM
#          value: claim-claim-token #optional
#        - name: ADVERITSE_IP
#          value: https://0.0.0.0:32400
        volumeMounts:
        - name: plex-config
          mountPath: "/config"
        - name: plex-content
          mountPath: "/media"
        - name: plex-transcode
          mountPath: "/transcode"
        resources:
          requests:
            memory: "2Gi"
            cpu: "2000m"
          limits:
            gpu.intel.com/i915: 1
      volumes:
      - name: plex-config
        persistentVolumeClaim:
          claimName: plex-config
      - name: plex-transcode
        persistentVolumeClaim:
          claimName: plex-transcode
      nodeSelector:
        hevc10: "true"
  volumeClaimTemplates:
  - metadata:
      name: plex-content
    spec:
      volumeName: plex-content
      accessModes: ["ReadWriteMany"]
      storageClassName: nfs
      resources:
        requests:
          storage: 1Gi
