## Service
---
apiVersion: v1
kind: Service
metadata:
   name: lidarr
   labels:
     app.kubernetes.io/name: lidarr
spec:
  type: ClusterIP
  #clusterIP: None
  ports:
  - port: 8686
  selector:
    app.kubernetes.io/name: lidarr
    