---
apiVersion: v1
kind: Service
metadata:
   name: radarr
   namespace: mediaserver
   labels:
     app: radarr
spec:
  type: LoadBalancer
  #externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 7878
    name: http-7878
  selector:
    app: radarr
--- 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: radarr
  serviceName: "radarr"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: radarr
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr:latest
        ports:
        - containerPort: 7878
          name: http-7878
        volumeMounts:
        - name: radarr-config
          mountPath: "/config"
        - name: radarr-downloads
          mountPath: "/downloads"
        - name: radarr-content
          mountPath: "/media"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: radarr-config
        persistentVolumeClaim:
          claimName: radarr-config
  volumeClaimTemplates:
  - metadata:
      name: radarr-downloads
    spec:
      volumeName: radarr-downloads
      accessModes: ["ReadWriteMany"]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: radarr-content
    spec:
      volumeName: radarr-content
      accessModes: ["ReadWriteMany"]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 1Gi
