## Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  namespace: mediaserver
spec:
  ingressClassName: traefik-internal
  rules:
  - host: sonarr.mediaserver.k8s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  sonarr
            port:
              number: 8989
              
              
## Service
---
apiVersion: v1
kind: Service
metadata:
   name: sonarr
   namespace: mediaserver
   labels:
     app: sonarr
spec:
  clusterIP: None
  ports:
  - port: 8989
  selector:
    app: sonarr


## Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: sonarr
  serviceName: "sonarr"
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/sonarr:latest
        ports:
        - containerPort: 8989
          name: http-8989
        volumeMounts:
        - name: sonarr-config
          mountPath: "/config"
        - name: downloads
          mountPath: "/downloads"
        - name: media
          mountPath: "/media"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: sonarr-config
        persistentVolumeClaim:
          claimName: sonarr-config
      - name: downloads
        nfs:
          path: /mnt/pool0/downloads
          server: spielberg.farhoodliquor.dmz
      - name: media
        nfs:
          path: /mnt/pool0/media
          server: spielberg.farhoodliquor.dmz


## Volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: mediaserver
  labels:
    name: sonarr-config
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
