## Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  namespace: mediaserver
spec:
  ingressClassName: traefik-internal
  rules:
  - host: sonarr.mediaserver.k8s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  sonarr
            port:
              number: 8989
              
              
## Service
---
apiVersion: v1
kind: Service
metadata:
   name: sonarr
   namespace: mediaserver
   labels:
     app: sonarr
spec:
  type: ClusterIP
  #clusterIP: None
  ports:
  - port: 8989
  selector:
    app: sonarr


## StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarr
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: sonarr
  serviceName: "sonarr"
  replicas: 0
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/sonarr:latest
        ports:
        - containerPort: 8989
          name: http-8989
        volumeMounts:
        - name: sonarr-config
          mountPath: "/config"
        - name: sonarr-remotemedia
          mountPath: "/media/remote"
        - name: shows
          mountPath: "/media/shows"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: sonarr-config
        persistentVolumeClaim:
          claimName: sonarr-config
      - name: sonarr-remotemedia
        persistentVolumeClaim:
          claimName: sonarr-farhoodliquor-remotemedia
      - name: shows
        nfs:
          path: /mnt/pool2/media/shows
          server: spielberg.farhoodliquor.dmz


## Volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: mediaserver
  labels:
    name: sonarr-config
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-perpetual
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-farhoodliquor-remotemedia
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rclone
  selector:
    matchLabels:
      name: sonarr-farhoodliquor-remotemedia
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-farhoodliquor-remotemedia-pv
  labels:
    name: sonarr-farhoodliquor-remotemedia
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  storageClassName: rclone
  csi:
    driver: csi-rclone
    volumeHandle: data-id
    volumeAttributes:
      remote: "http"
      remotePath: "/"
      webdav-url: "http://zurg.mediaserver.k8s/http/"