## Service
---
apiVersion: v1
kind: Service
metadata:
   name: sonarr
   namespace: mediaserver
   labels:
     app: sonarr
spec:
  type: LoadBalancer
  #externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 8989
    name: http-8989
  selector:
    app: sonarr


## StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarr
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: sonarr
  serviceName: "sonarr"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/sonarr:latest
        ports:
        - containerPort: 8989
          name: http-8989
        volumeMounts:
        - name: sonarr-config
          mountPath: "/config"
        - name: sonarr-downloads
          mountPath: "/downloads"
        - name: sonarr-content
          mountPath: "/media"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: sonarr-config
        persistentVolumeClaim:
          claimName: sonarr-config
  volumeClaimTemplates:
  - metadata:
      name: sonarr-downloads
    spec:
      volumeName: sonarr-downloads
      accessModes: ["ReadWriteMany"]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: sonarr-content
    spec:
      volumeName: sonarr-content
      accessModes: ["ReadWriteMany"]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 1Gi


## Volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: mediaserver
  labels:
    name: sonarr-config
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-downloads
  labels:
    name: sonarr-downloads
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/downloads/
    server: spielberg.farhoodliquor.dmz
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-content
  labels:
    name: sonarr-content
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/media/
    server: spielberg.farhoodliquor.dmz