## StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rdtclient
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rdtclient
  serviceName: "rdtclient"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rdtclient
    spec:
      containers:
      - name: rdtclient
        image: rogerfar/rdtclient:latest
        ports:
        - containerPort: 6500
          name: http-6500
        volumeMounts:
        - name: db
          mountPath: "/data/db"
        - name: local
          mountPath: /media/local
        - name: remote
          mountPath: "/media/remote"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: local
        nfs:
          path: /mnt/pool0/media
          server: truenas.farhoodliquor.dmz
      - name: remote
        persistentVolumeClaim:
          claimName: mediaserver-remote
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi

## Volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rdtclient-db
  namespace: mediaserver
  labels:
    name: rdtclient-db
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-perpetual
  resources:
    requests:
      storage: 8Gi
---
