apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
  serviceName: "radarr"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radarr
    spec:
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7878
          name: http-7878
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: backups
          mountPath: "/backups"
        - name: movies
          mountPath: /media/movies
        - name: downloads
          mountPath: "/downloads"
        resources:
          requests:
            memory: "4Gi"
            cpu: "100m"
          limits:
            memory: "8Gi"
            cpu: "2000m"
      volumes:
      - name: backups
        persistentVolumeClaim:
          claimName: backups
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads
      - name: movies
        persistentVolumeClaim:
          claimName: movies
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi
