apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: handbrake
  labels:
    app.kubernetes.io/name: handbrake
  annotations:
    polaris.fairwinds.com/tagNotSpecified-exempt: true  
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: handbrake
  serviceName: "handbrake"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: handbrake
    spec:
      containers:
      - name: handbrake
        image: jlesage/handbrake:latest
        ports:
        - name: http-5800
          containerPort: 5800
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: shows0
          mountPath: "/media/shows0/"
        - name: movies0
          mountPath: "/media/movies0/"
        env:
        - name: "USER_ID"
          value: "911"
        - name: "GROUP_ID"
          value: "911"
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            gpu.intel.com/i915: 1
        readinessProbe:                # Check that the http server is responding to ensure the container is up
          httpGet:
            path: /
            port: http-5800
        livenessProbe:                 # Check that the chose torrent is available to ensure the container is serving data
          httpGet:
            path: /
            port: http-5800
          failureThreshold: 6
        securityContext:
          runAsRoot: false
          allowPrivilegeEscalation: false
      volumes:
      - name: movies0
        persistentVolumeClaim:
          claimName: movies0
      - name: shows0
        persistentVolumeClaim:
          claimName: shows0
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: farh.net/intel-gpu-gen
                operator: Gt
                values:
                - "11"
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi