apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: transmission-movies
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: transmission-movies
  template:
    metadata:
      labels:
        app.kubernetes.io/name: transmission-movies
    spec:
      containers:
      - name: transmission
        image: haugene/transmission-openvpn:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9091
          name: http-9091
        envFrom:
        - configMapRef:
            name: transmission-movies-config
        - secretRef:
            name: openvpn-credentials
        - secretRef:
            name: transmission-credentials
#        livenessProbe:
#          failureThreshold: 3
#          initialDelaySeconds: 10
#          periodSeconds: 2
#          successThreshold: 1
#          tcpSocket:
#            port: 9091
#          timeoutSeconds: 2
#       readinessProbe:
#          failureThreshold: 3
#          initialDelaySeconds: 10
#          periodSeconds: 2
#          successThreshold: 2
#          tcpSocket:
#            port: 9091
#          timeoutSeconds: 2
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            memory: 8Gi
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: movies0
          mountPath: /media/movies0
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: movies0
        persistentVolumeClaim:
          claimName: movies0
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi
