## StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr
  serviceName: "sonarr"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sonarr
    spec:
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/sonarr:latest
        ports:
        - containerPort: 8989
          name: http-8989
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: shows
          mountPath: /media/shows
        - name: downloads
          mountPath: "/downloads"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
      volumes:
      - name: shows
        nfs:
          path: /mnt/pool1/media/shows
          server: spielberg.dmz.farh.net
      - name: downloads
        nfs:
          server: spielberg.dmz.farh.net
          path: /mnt/pool0/downloads
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi

