## StatefulsSet
--- 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
  serviceName: "radarr"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radarr
    spec:
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7878
          name: http-7878
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: remote
          mountPath: "/media/remote"
        - name: local
          mountPath: /media/local
        - name: downloads
          mountPath: "/downloads"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: local
        nfs:
          path: /mnt/pool0/media
          server: truenas.farhoodliquor.dmz
      - name: remote
        persistentVolumeClaim:
          claimName: mediaserver-remote
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi
