apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tdarr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tdarr
  serviceName: "tdarr"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tdarr
    spec:
      containers:
      - name: tdarr
        image: lscr.io/linuxserver/tdarr:latest
        ports:
        - containerPort: 8989
          name: http-8989
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: backups
          mountPath: "/backups"
        - name: shows
          mountPath: /media/shows
        - name: downloads
          mountPath: "/downloads"
        resources:
          requests:
            memory: "4Gi"
            cpu: "1000m"
          limits:
            memory: "8Gi"
      volumes:
      - name: backups
        persistentVolumeClaim:
          claimName: backups
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads
      - name: shows
        persistentVolumeClaim:
          claimName: shows
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi


