apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex-livetv
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: plex-livetv
  serviceName: "plex-livetv"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plex-livetv
    spec:
      containers:
      - name: plex
        image: docker.io/plexinc/pms-docker:plexpass
        imagePullPolicy: Always
        ports:
        - containerPort: 32400
          name: http-32400
        env:
        - name: TZ
          value: America/Detroit
        - name: VERSION
          value: docker
        - name: PLEX_UID
          value: "911"
        - name: PLEX_GID
          value: "911"
        - name: PLEX_CLAIM
          value: claim-s5ze8dETkas9PNJ9YkPk
        - name: ADVERITSE_IP
          value: https://65.43.40.106
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: transcode
          mountPath: "/transcode"
        - name: recordings
          mountPath: "/media/local/recordings"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "3000m"
            gpu.intel.com/i915: 1
        readinessProbe:                # Check that the http server is responding to ensure the container is up
          tcpSocket:
            port: 32400
        livelinessProbe:               # Check that the http server is responding to ensure the container is up
          tcpSocket:
            port: 32400
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 5
      volumes:
      - name: transcode
        emptyDir: 
          sizeLimit: 128Gi
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 32Gi
  - metadata:
      name: recordings
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 256Gi