apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qbittorrent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent
  serviceName: "qbittorrent"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qbittorrent
    spec:
      initContainers:
        - name: copy-openvpn-config
          image: busybox
          command:
            - "/bin/sh"
            - "-c"
            - |
              echo "Copying OpenVPN configuration files..."
              mkdir -p /config/openvpn
              cp -L /configmap/* /config/openvpn/
              echo "Copy completed."
          volumeMounts:
            - name: openvpn-config
              mountPath: "/configmap" # Mount ConfigMap data
            - name: config
              mountPath: "/config" # Persistent storage
      containers:
        - name: qbittorrent
          image: trigus42/qbittorrentvpn:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # Web UI
              name: web-ui
            - containerPort: 8999 # Torrent port
              name: torrent-tcp
            - containerPort: 8999
              protocol: UDP
              name: torrent-udp
          envFrom:
            - configMapRef:
                name: qbittorrent-config
            - secretRef:
                name: openvpn-credentials
          volumeMounts:
            - name: config
              mountPath: "/config"
            - name: downloads
              mountPath: /downloads
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
      volumes:
        - name: openvpn-config
          configMap:
            name: qbittorrent-ovpn
            defaultMode: 0777 # Ensure proper permissions
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 4Gi
