apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: transmission-movies
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  serviceName: transmission-movies
  selector:
    matchLabels:
      app.kubernetes.io/name: transmission-movies
  template:
    metadata:
      labels:
        app.kubernetes.io/name: transmission-movies
    spec:
      initContainers:
      - name: copy-openvpn-config
        image: busybox:1.36
        command:
          - /bin/sh
          - -c
          - |
            cp /tmp/openvpn/*.ovpn /etc/openvpn/custom/
            cp /tmp/openvpn/*.sh /etc/openvpn/custom/
            chmod +x /etc/openvpn/custom/*.sh
        volumeMounts:
        - name: openvpn-config
          mountPath: /tmp/openvpn
        - name: openvpn-custom
          mountPath: /etc/openvpn/custom
      containers:
      - name: transmission
        image: haugene/transmission-openvpn:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9091
          name: http-9091
        envFrom:
        - configMapRef:
            name: transmission-movies-config
        - secretRef:
            name: protonvpn-credentials
        - secretRef:
            name: transmission-credentials
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            memory: 8Gi
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: openvpn-custom
          mountPath: /etc/openvpn/custom
        - name: movies0
          mountPath: /media/movies0
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: openvpn-config
        configMap:
          name: transmission-movies-config
          items:
          - key: openvpn-config.ovpn
            path: openvpn-config.ovpn
          - key: update-port.sh
            path: update-port.sh
      - name: openvpn-custom
        emptyDir: {}
      - name: movies0
        persistentVolumeClaim:
          claimName: movies0
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi
