apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rdtclient
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rdtclient
  serviceName: "rdtclient"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rdtclient
    spec:
      containers:
      - name: rdtclient
        image: rogerfar/rdtclient:latest
        ports:
        - containerPort: 6500
          name: http-6500
        volumeMounts:
        - name: db
          mountPath: "/data/db"
        - name: local
          mountPath: /media/local
        - name: downloads
          mountPath: "/downloads"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
      volumes:
      - name: local
        nfs:
          path: /mnt/pool0/media
          server: spielberg.dmz.farh.net
      - name: downloads
        nfs:
          server: spielberg.dmz.farh.net
          path: /mnt/pool0/downloads
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi