## StatefulsSet
--- 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
  serviceName: "radarr"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radarr
    spec:
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7878
          name: http-7878
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: backups
          mountPath: "/backups"
        - name: movies
          mountPath: /media/movies
        - name: downloads
          mountPath: "/downloads"
        resources:
          requests:
            memory: "4Gi"
            cpu: "250m"
          limits:
            memory: "8Gi"
            cpu: "1000m"
      volumes:
      - name: backups
        nfs:
          server: spielberg.dmz.farh.net
          path: /mnt/pool0/backups/radarr
      - name: movies
        nfs:
          path: /mnt/pool1/media/movies
          server: spielberg.dmz.farh.net
#      - name: downloads
#        nfs:
#          server: spielberg.dmz.farh.net
#          path: /mnt/pool0/downloads
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi
