apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qbittorrent-shows
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  serviceName: qbittorrent-shows
  selector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent-shows
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qbittorrent-shows
    spec:
      containers:
      - name: qbittorrent
        image: dyonr/qbittorrentvpn:latest
        #image: lscr.io/linuxserver/qbittorrent:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: webui-8080
        - containerPort: 9000
          name: tracker-9000
        - containerPort: 8999
          name: btttcp-8999
        - containerPort: 8999
          name: bttudp-8999
          protocol: UDP
        envFrom:
        - configMapRef:
            name: qbittorrent-shows-config
        - secretRef:
            name: protonvpn-credentials
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            memory: 8Gi
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: shows0
          mountPath: /media/shows0
      volumes:
      - name: shows0
        persistentVolumeClaim:
          claimName: shows0
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi
