apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: whisparr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: whisparr
  serviceName: "whisparr"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: whisparr
    spec:
      containers:
      - name: whisparr
        image: ghcr.io/hotio/whisparr:latest
        ports:
        - containerPort: 6969
          name: http-6969
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: backups
          mountPath: "/backups"
        - name: adult
          mountPath: /media/adult
        - name: adult-old
          mountPath: /media/adult-old
        - name: downloads
          mountPath: "/downloads"
        env:
        - name: PUID
          value: "911"
        - name: PGID
          value: "911"
        resources:
          requests:
            memory: "4Gi"
            cpu: "250m"
          limits:
            memory: "8Gi"
            cpu: "1000m"
      volumes:
      - name: backups
        persistentVolumeClaim:
          claimName: backups
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads
      - name: adult
        persistentVolumeClaim:
          claimName: adult
      - name: adult-old
        persistentVolumeClaim:
          claimName: adult-old
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi


