apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tautulli
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tautulli
  serviceName: "tautulli"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tautulli
    spec:
      containers:
      - name: tautulli
        image: ghcr.io/tautulli/tautulli:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8181
          name: http-8181
        volumeMounts:
        - name: config
          mountPath: "/config"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 8Gi
