apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr
  serviceName: "sonarr"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sonarr
    spec:
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/sonarr:latest
        ports:
        - containerPort: 8989
          name: http-sonarr
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: backups
          mountPath: "/backups"
        - name: shows0
          mountPath: /media/shows0
        - name: shows
          mountPath: /media/shows
        - name: downloads
          mountPath: "/downloads"
        - name: temp-shows
          mountPath: /media/temp-shows
        resources:
          requests:
            memory: "4Gi"
            cpu: "1000m"
          limits:
            memory: "8Gi"
        livenessProbe:
          httpGet:
            path: /ping
            port: http-sonarr
        readinessProbe:
          httpGet:
            path: /ping
            port: http-sonarr
      volumes:
      - name: backups
        persistentVolumeClaim:
          claimName: backups
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads
      - name: shows0
        persistentVolumeClaim:
          claimName: shows0
      - name: shows
        persistentVolumeClaim:
          claimName: shows
      - name: temp-shows
        persistentVolumeClaim:
          claimName: temp-shows
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50  # Higher weight increases preference
              preference:
                matchExpressions:
                  - key: node_high_throughput
                    operator: In
                    values:
                      - "true"
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi


