apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qbitorrent-movies
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  serviceName: qbitorrent-movies
  selector:
    matchLabels:
      app.kubernetes.io/name: qbitorrent-movies
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qbitorrent-movies
    spec:
      containers:
      - name: qbitorrent
        image: dyonr/qbittorrentvpn:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http-8080
        envFrom:
        - configMapRef:
            name: qbitorrent-movies-config
        - secretRef:
            name: protonvpn-credentials
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            memory: 8Gi
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: movies0
          mountPath: /media/movies0
      volumes:
      - name: movies0
        persistentVolumeClaim:
          claimName: movies0
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi
