apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prowlarr
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prowlarr
  serviceName: "prowlarr"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prowlarr
    spec:
      containers:
      - name: prowlarr
        image: lscr.io/linuxserver/prowlarr:latest
        ports:
        - name: http-prowlarr
          containerPort: 9696
        volumeMounts:
        - name: config
          mountPath: "/config"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        readinessProbe:                # Check that the http server is responding to ensure the container is up
          httpGet:
            path: /ping
            port: http-prowlarr
        livelinessProbe:               # Check that the http server is responding to ensure the container is up
          httpGet:
            path: /ping
            port: http-prowlarr
            failureThreshold: 5
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi

