apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sabnzbd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sabnzbd
  serviceName: "sabnzbd"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sabnzbd
    spec:
      containers:
      - name: sabnzbd
        image: lscr.io/linuxserver/sabnzbd:latest
        ports:
        - containerPort: 8080
          name: http-8080
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: downloads
          mountPath: "/downloads"
        - name: backups
          mountPath: "/backups"
        resources:
          requests:
            memory: "4Gi"
            cpu: "250m"
          limits:
            memory: "8Gi"
            cpu: "1000m"
      volumes:
      - name: backups
        persistentVolumeClaim:
          claimName: backups
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads
volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi
  - metadata:
      name: config-new
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi
      storageClassName: longhorn-perpetual