## Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tautulli
  namespace: mediaserver
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect@kubernetescrd
spec:
  ingressClassName: traefik-external
  rules:
  - host: stats.farhoodliquor.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  tautulli
            port:
              number: 8181
  tls:
  - hosts:
    - stats.farhoodliquor.com
    secretName: farhoodliquor-com-cert-letsencrypt-prod


## Service
---
apiVersion: v1
kind: Service
metadata:
   name: tautulli
   namespace: mediaserver
   labels:
     app: tautulli
spec:
  clusterIP: None
  ports:
  - port: 8181
  selector:
    app: tautulli


## Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: tautulli
  serviceName: "tautulli"
  replicas: 1
  template:
    metadata:
      labels:
        app: tautulli
    spec:
      containers:
      - name: tautulli
        image: lscr.io/linuxserver/tautulli:latest
        ports:
        - containerPort: 8181
          name: http-8181
        volumeMounts:
        - name: tautulli-config
          mountPath: "/config"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: tautulli-config
        persistentVolumeClaim:
          claimName: tautulli-config


## Volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config
  namespace: mediaserver
  labels:
    name: tautulli-config
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi