## Service
---
apiVersion: v1
kind: Service
metadata:
   name: tautulli
   namespace: mediaserver
   labels:
     app.kubernetes.io/name: tautulli
spec:
  clusterIP: None
  ports:
  - port: 8181
  selector:
    app.kubernetes.io/name: tautulli


## StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tautulli
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tautulli
  serviceName: "tautulli"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tautulli
    spec:
      containers:
      - name: tautulli
        image: ghcr.io/tautulli/tautulli:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8181
          name: http-8181
        volumeMounts:
        - name: tautulli-config
          mountPath: "/config"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
      volumes:
      - name: tautulli-config
        persistentVolumeClaim:
          claimName: tautulli-config


## Volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config
  namespace: mediaserver
  labels:
    name: tautulli-config
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-perpetual
  resources:
    requests:
      storage: 4Gi