
## ConfigMaps
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission-config
  namespace: mediaserver
data:
  LOCAL_NETWORK: "10.0.0.0/8"
  OPENVPN_COUNTRY: US
  OPENVPN_CITY: Detroit
  OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
  OPENVPN_PROVIDER: NORDVPN
  NORDVPN_COUNTRY: US
  NORDVPN_CATEGORY: legacy_p2p
  NORDVPN_PROTOCOL: udp
  #NORDVPN_SERVER: us6272.nordvpn.com
  TRANSMISSION_DOWNLOAD_QUEUE_SIZE: "8"
  TRANSMISSION_RATIO_LIMIT: "2"
  TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
  TRANSMISSION_SPEED_LIMIT_DOWN: "100000"
  TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED: "true"
  TRANSMISSION_SPEED_LIMIT_UP: "10000"
  TRANSMISSION_SPEED_LIMIT_UP_ENABLED: "true"
  WEBPROXY_ENABLED: "false"
  #CREATE_TUN_DEVICE: "true"


## Service
---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: mediaserver
spec:
  selector:
    app:  transmission
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9091
  sessionAffinity: None
  type: LoadBalancer


## Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: mediaserver
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: transmission
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
        envFrom:
        - secretRef:
          name: vpn-creds
        - configMapRef:
          name: transmission-config
        image: haugene/transmission-openvpn:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          tcpSocket:
            port: 9091
          timeoutSeconds: 2
        name: transmission
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 2
          tcpSocket:
            port: 9091
          timeoutSeconds: 2
        resources:
          limits:
            memory: 2000Mi
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
        volumeMounts:
        - name: transmission-config
          mountPath: "/config"
        - name: downloads
          mountPath: /downloads
        #- name: tunnel
        #  mountPath: /dev/net/tun
        #  readOnly: true
        - name: localtime
          mountPath: /etc/localtime 
          readOnly: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: transmission-config
        persistentVolumeClaim:
          claimName: transmission-config
      - name: downloads
        nfs:
          path: /mnt/pool0/downloads
          server: spielberg.farhoodliquor.dmz
      #- name: tunnel
      #  hostPath:
      #    path: /dev/net/tun
      #- name: localtime
      #  hostPath:
      #    path: /etc/localtime
      #    type: ""        


## Volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config
  labels:
    name: transmission-config
  namespace: mediaserver
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
