---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  labels:
    name: downloads
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ ReadWriteMany ]
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adult
  labels:
    name: adult
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ ReadWriteMany ]
  storageClassName: ceph-media
  resources:
    requests:
      storage: 2Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shows-ceph
  labels:
    name: shows-ceph
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ ReadWriteMany ]
  storageClassName: ceph-media
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies-ceph
  labels:
    name: movies-ceph
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ ReadWriteMany ]
  storageClassName: ceph-media
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backups-pv
spec:
  capacity:
    storage: 1Gi  # Adjust based on actual requirement
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-client"
  nfs:
    server: spielberg.dmz.farh.net
    path: /mnt/main-pool/backups/mediaserver
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backups
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-client"
  resources:
    requests:
      storage: 1Gi  # Must match or be less than the PV capacity
  volumeName: backups-pv
---  
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies-pv
spec:
  capacity:
    storage: 1Gi  # Adjust based on actual requirement
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-client"
  nfs:
    server: spielberg.dmz.farh.net
    path: /mnt/pool0/media/movies
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-client"
  resources:
    requests:
      storage: 1Gi  # Must match or be less than the PV capacity
  volumeName: movies-pv
---  
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies1-pv
spec:
  capacity:
    storage: 1Gi  # Adjust based on actual requirement
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-client"
  nfs:
    server: spielberg.dmz.farh.net
    path: /mnt/pool1/media/movies
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-client"
  resources:
    requests:
      storage: 1Gi  # Must match or be less than the PV capacity
  volumeName: movies1-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shows-pv
spec:
  capacity:
    storage: 1Gi  # Adjust based on actual requirement
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-client"
  nfs:
    server: spielberg.dmz.farh.net
    path: /mnt/pool1/media/shows
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shows
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-client"
  resources:
    requests:
      storage: 1Gi  # Must match or be less than the PV capacity
  volumeName: shows-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shows0-pv
spec:
  capacity:
    storage: 1Gi  # Adjust based on actual requirement
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-client"
  nfs:
    server: spielberg.dmz.farh.net
    path: /mnt/pool0/media/shows
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shows0
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-client"
  resources:
    requests:
      storage: 1Gi  # Must match or be less than the PV capacity
  volumeName: shows0-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: temp-movies
  labels:
    name: temp-movies
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ ReadWriteMany ]
  storageClassName: temp-media
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: temp-shows
  labels:
    name: temp-shows
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ ReadWriteMany ]
  storageClassName: temp-media
  resources:
    requests:
      storage: 10Ti