---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: mediaserver
  labels:
    name: downloads
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ ReadWriteMany ]
  storageClassName: longhorn-perpetual
  resources:
    requests:
      storage: 256Gi