### SABnzbd
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-farhoodliquor-config
  labels:
    name: sabnzbd-farhoodliquor-config
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-farhoodliquor-downloads
  labels:
    name: sabnzbd-farhoodliquor-downloads
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/downloads/
    server: spielberg.farhoodliquor.dmz
### EndSABnzbd


### Prowlarr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-farhoodliquor-config
  labels:
    name: prowlarr-farhoodliquor-config
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
### End Prowlarr


### Sonarr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-farhoodliquor-config
  labels:
    name: sonarr-farhoodliquor-config
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-farhoodliquor-downloads
  labels:
    name: sonarr-farhoodliquor-downloads
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/downloads/
    server: spielberg.farhoodliquor.dmz
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-farhoodliquor-content
  labels:
    name: sonarr-farhoodliquor-content
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/media/
    server: spielberg.farhoodliquor.dmz
### End Sonarr


### Radarr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-farhoodliquor-config
  labels:
    name: radarr-farhoodliquor-config
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-farhoodliquor-downloads
  labels:
    name: radarr-farhoodliquor--downloads
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/downloads/
    server: spielberg.farhoodliquor.dmz
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-farhoodliquor-content
  labels:
    name: radarr-farhoodliquor-content
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/media/
    server: spielberg.farhoodliquor.dmz
### End Radarr

### Readarr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: readarr-farhoodliquor-config
  labels:
    name: readarr-farhoodliquor-config
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: readarr-farhoodliquor-downloads
  labels:
    name: readarr-farhoodliquor-downloads
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/downloads/
    server: spielberg.farhoodliquor.dmz
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: readarr-farhoodliquor-content
  labels:
    name: readarr-farhoodliquor-content
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/media/
    server: spielberg.farhoodliquor.dmz
### End Readarr


### Plex
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-farhoodliquor-config
  labels:
    name: plex-farhoodliquor-config
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-farhoodliquor-content
  labels:
    name: plex-farhoodliquor-content
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/media/
    server: spielberg.farhoodliquor.dmz
### End Plex

### Jellyfin
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-farhoodliquor-config
  labels:
    name: jellyfin-farhoodliquor-config
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/jellyfin/config/
    server: spielberg.farhoodliquor.dmz
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-farhoodliquor-content
  labels:
    name: jellyfin-farhoodliquor-content
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/media/
    server: spielberg.farhoodliquor.dmz
### End Jellyfin