## Physical Volumes
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileserver-data-pv
  labels:
    name: fileserver-data
spec:
  capacity:
    storage: 128Gi
  volumeMode: Filesystem
  accessModes: [ ReadWriteOnce ]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-perpetual
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: fileserver-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediaserver-remote-pv
  labels:
    name: mediaserver-remote
spec:
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  storageClassName: rclone
  csi:
    driver: csi-rclone
    volumeHandle: data-id
    volumeAttributes:
      remote: "http"
      remotePath: "/http/"
      http-url: "http://zurg.mediaserver.k8s/http/"
      attr-timeout: "1h"
      buffer-size: "1MiB"
      vfs-disk-space-total-size: "10PiB"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: riven-db-pv
  labels:
    name: riven-db
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes: [ ReadWriteOnce ]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-perpetual
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: riven-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: riven-config-pv
  labels:
    name: riven-config
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes: [ ReadWriteOnce ]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-perpetual
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: riven-config
---


## Volume Claims
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileserver-data
  labels:
    name: fileserver-data
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ ReadWriteOnce ]
  storageClassName: longhorn-perpetual
  resources:
    requests:
      storage: 128Gi
  selector:
    matchLabels:
      name: fileserver-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediaserver-remote
spec:
  accessModes: [ ReadOnlyMany ]
  storageClassName: rclone
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: mediaserver-remote
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: riven-db
  labels:
    name: riven-db
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ ReadWriteOnce ]
  storageClassName: longhorn-perpetual
  resources:
    requests:
      storage: 8Gi
  selector:
    matchLabels:
      name: riven-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: riven-config
  labels:
    name: riven-config
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ ReadWriteOnce ]
  storageClassName: longhorn-perpetual
  resources:
    requests:
      storage: 8Gi
  selector:
    matchLabels:
      name: riven-config
---
