---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  labels:
    name: downloads
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ ReadWriteMany ]
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backups
  labels:
    name: backups
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ ReadWriteMany ]
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 32Gi