### SABnzbd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config
  labels:
    name: sabnzbd-config
  namespace: mediaserver
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-downloads
  labels:
    name: sabnzbd-downloads
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/downloads/
    server: spielberg.farhoodliquor.dmz
### EndSABnzbd


### Prowlarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: mediaserver
  labels:
    name: prowlarr-config
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
### End Prowlarr

### Overseer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseer-config
  namespace: mediaserver
  labels:
    name: overseer-config
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
### End Overseer


### Sonarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: mediaserver
  labels:
    name: sonarr-config
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-downloads
  labels:
    name: sonarr-downloads
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/downloads/
    server: spielberg.farhoodliquor.dmz
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-content
  labels:
    name: sonarr-content
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/media/
    server: spielberg.farhoodliquor.dmz
### End Sonarr


### Radarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: mediaserver
  labels:
    name: radarr-config
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-downloads
  labels:
    name: radarr-downloads
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/downloads/
    server: spielberg.farhoodliquor.dmz
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-content
  labels:
    name: radarr-content
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/media/
    server: spielberg.farhoodliquor.dmz
### End Radarr

### Lidarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config
  namespace: mediaserver
  labels:
    name: lidarr-config
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-downloads
  labels:
    name: lidarr-downloads
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/downloads/
    server: spielberg.farhoodliquor.dmz
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-content
  labels:
    name: lidarr-content
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/media/
    server: spielberg.farhoodliquor.dmz
### End Lidarr


### Readarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-config
  namespace: mediaserver
  labels:
    name: readarr-config
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: readarr-downloads
  labels:
    name: readarr-downloads
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/downloads/
    server: spielberg.farhoodliquor.dmz
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: readarr-content
  labels:
    name: readarr-content
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/media/
    server: spielberg.farhoodliquor.dmz
### End Readarr


### Plex
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: mediaserver
  labels:
    name: plex-config
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-transcode
  namespace: mediaserver
  labels:
    name: plex-transcode
  annotations:
    kustomize.toolkit.fluxcd.io/prune: enabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-content
  labels:
    name: plex-content
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/media/
    server: spielberg.farhoodliquor.dmz
### End Plex

### Jellyfin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: mediaserver
  labels:
    name: jellyfin-config
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-transcode
  namespace: mediaserver
  labels:
    name: jellyfin-transcode
  annotations:
    kustomize.toolkit.fluxcd.io/prune: enabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-content
  labels:
    name: jellyfin-content
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/media/
    server: spielberg.farhoodliquor.dmz
### End Jellyfin