---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-farhoodliquor-movies-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - soft
    - rsize=32768
    - wsize=32768
  nfs:
    path: /mnt/pool1/media/movies
    server: spielberg.farhoodliquor.dmz
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-farhoodliquor-shows-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - soft
    - rsize=32768
    - wsize=32768
  nfs:
    path: /mnt/pool2/media/shows
    server: spielberg.farhoodliquor.dmz
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zurg-remotemedia
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rclone
  selector:
    matchLabels:
      name: zurg-remotemedia
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zurg-remotemedia-pv
  labels:
    name: zurg-remotemedia
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  storageClassName: rclone
  csi:
    driver: csi-rclone
    volumeHandle: data-id
    volumeAttributes:
      remote: "http"
      remotePath: "/http/"
      http-url: "http://zurg.mediaserver.k8s/http/"
      attr-timeout: "1h"
      buffer-size: "128KiB"
      max-read-ahead: "1MiB"
      cache-dir: "/tmp/rclone/zurg/"
      vfs-cache-mode: "full"
      vfs-read-ahead: "1MiB"
      vfs-cache-max-size: "32GiB"
      vfs-disk-space-total-size: "10PiB"