---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clusterplex-cache-pvc
  labels:
    name: clusterplex-cache-pvc
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ ReadWriteMany ]
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clusterplex-cache-pvc
  labels:
    name: clusterplex-cache-pvc
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ ReadWriteMany ]
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 4Gi
