---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  labels:
    name: downloads
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ ReadWriteMany ]
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backups-pv
spec:
  capacity:
    storage: 1Gi  # Adjust based on actual requirement
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    server: spielberg.dmz.farh.net
    path: /mnt/pool0/backups/mediaserver
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backups
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi  # Must match or be less than the PV capacity
  volumeName: backups-pv
