
## Service
---
apiVersion: v1
kind: Service
metadata:
   name: zurg-test
   namespace: mediaserver
   labels:
     app: zurg-test
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 9999
  selector:
    app: zurg-test


## StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zurg-test
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: zurg-test
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
           matchExpressions:
            - key: <label-key>
              operator: In
              values:
              - <label-value>
          topologyKey: kubernetes.io/hostname
  serviceName: "zurg-test"
  replicas: 2
  template:
    metadata:
      labels:
        app: zurg-test
    spec:
      containers:
      - name: zurg
        image: ghcr.io/debridmediamanager/zurg-testing:latest
        ports:
        - containerPort: 9999
          name: http-9999
        volumeMounts:
        - name: zurg-data
          mountPath: "/app/data"
        - name: zurg-config
          mountPath: /app/config.yml
          subPath: config.yml
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 9999
          initialDelaySeconds: 5       # Start probing after 1 minute (adjust as needed)
          periodSeconds: 5             # Check every 30 seconds
          successThreshold: 1           # Ready when the probe succeeds once
          timeoutSeconds: 4            # Timeout after 10 seconds per attempt
        livenessProbe:
          httpGet:
            path: /http/__unplayable__/ubuntu-24.04.1-live-server-amd64.iso/
            port: 9999
          initialDelaySeconds: 60       # Start probing after 1 minute (adjust as needed)
          periodSeconds: 30             # Check every 30 seconds
          failureThreshold: 30          # After 30 checks (~15 minutes) fail the liveness check
          successThreshold: 3           # Ready when the probe succeeds once
          timeoutSeconds: 10            # Timeout after 10 seconds per attempt
      volumes:
      - name: zurg-config
        secret:
          secretName: zurg-config
          items:
          - key: config.yml
            path: config.yml
  volumeClaimTemplates:
  - metadata:
      name: zurg-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: longhorn-perpetual
      resources:
        requests:
          storage: 4Gi
      selector:
        matchLabels:
          name: zurg-data