## Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zurg
  namespace: mediaserver
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect@kubernetescrd
spec:
  ingressClassName: traefik-internal
  rules:
  - host: zurg.mediaserver.k8s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  zurg
            port:
              number: 9999
  tls:
  - hosts:
    - requests.farhoodliquor.com
    secretName: farhoodliquor-com-cert-letsencrypt-prod


## Service
---
apiVersion: v1
kind: Service
metadata:
   name: zurg
   namespace: mediaserver
   labels:
     app: zurg
spec:
  clusterIP: None
  ports:
  - port: 9999
  selector:
    app: zurg


## StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zurg
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: zurg
  serviceName: "zurg"
  replicas: 1
  template:
    metadata:
      labels:
        app: zurg
    spec:
      containers:
      - name: zurg
        image: ghcr.io/debridmediamanager/zurg-testing:latest
        ports:
        - containerPort: 9999
          name: http-9999
        volumeMounts:
        - name: zurg-data
          mountPath: "/app/data"
        - name: zurg-config
          mountPath: /app/config.yml
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: zurg-data
        persistentVolumeClaim:
          claimName: zurg-data
      - name: zurg-config
        secret:
          secretName: zurg-config

## Volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zurg-data
  namespace: mediaserver
  labels:
    name: zurg-data
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-perpetual
  resources:
    requests:
      storage: 8Gi
